[12:55 PM, 12/2/2024] Sharmili IT: pipeline {
    agent any
    environment {
        CI='true'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Running npm install...'
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Running test script...'
                bat '"C:\\Program Files\\Git\\bin\\bash.exe" ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                echo 'Delivering for development...'
                bat '"C:\\Program Files\\Git\\bin\\bash.exe" ./jenkins/scripts/deliver-for-development.sh'
                timeout(time: 5, unit: 'MINU…
[12:55 PM, 12/2/2024] Sharmili IT: pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                timeout(time: 5, unit: 'MINUTES') {
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                }
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                timeout(time: 5, unit: 'MINUTES') {
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                }
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}